# Generated by Django 3.0.8 on 2020-07-09 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoly', '0003_likedphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedphoto',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='photoly.Photo'),
        ),
    ]
