# Generated by Django 3.0.8 on 2020-07-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoly', '0004_auto_20200709_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPhoto',
        ),
    ]
