# Generated by Django 3.0.8 on 2020-07-09 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoly', '0005_delete_likedphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
