# Generated by Django 3.0.4 on 2020-10-06 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoly', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
