# Generated by Django 3.0.8 on 2020-10-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoly', '0010_auto_20201006_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='favourite',
        ),
        migrations.AddField(
            model_name='photo',
            name='favourite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
