# Generated by Django 3.0.8 on 2020-07-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20200707_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
